/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controlador;
import controller.DTOFarmacias;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Producto;
import model.Farmacia;


/**
 *
 * @author ericka
 */
public class FrmCatalogos extends javax.swing.JFrame {

   
    private DTOFarmacias dtoFarmacia = new DTOFarmacias();
    private Controlador elCtrl = Controlador.getInstance();
    
    
    /**
     * Creates new form FrmCatalogos
     */
    public FrmCatalogos() {
        initComponents();
        cargaTablaProductos();
        cargaTablaFarmacias();
    }

    private void cargaTablaProductos(){
        elCtrl.recuperarProductos();
        DefaultTableModel modelo = new DefaultTableModel(elCtrl.getdTOProductos().getLosProductos().size(), 4);
        for (int i = 0; i < elCtrl.getdTOProductos().getLosProductos().size(); i++) {
            Producto p = (Producto) elCtrl.getdTOProductos().getLosProductos().get(i);
            modelo.setValueAt(p.getCodigo(), i, 0);
            modelo.setValueAt(p.getDescripcion(), i, 1);
            modelo.setValueAt(p.getUnidadesReq(), i, 2);
            modelo.setValueAt(p.getPuntos(), i, 3);
        }
        jTable1.setModel(modelo);
    }
    
    private void cargaTablaFarmacias(){
       dtoFarmacia = elCtrl.recuperarFarmacias(dtoFarmacia);
       DefaultTableModel modelo = new DefaultTableModel(dtoFarmacia.getLasFarmacias().size(), 4);
       for (int i = 0; i < dtoFarmacia.getLasFarmacias().size(); i++) {
            Farmacia p = (Farmacia) dtoFarmacia.getLasFarmacias().get(i);
            modelo.setValueAt(p.getCodigo(), i, 0);
            modelo.setValueAt(p.getDescripcion(), i, 1);
            modelo.setValueAt(p.getTelefono(), i, 2);
        }
        tablaFarmacias.setModel(modelo);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelProductos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblCodigo = new javax.swing.JLabel();
        txtCodigoPrd = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        lblUnidades = new javax.swing.JLabel();
        spUnidades = new javax.swing.JSpinner();
        txtDescripcion = new javax.swing.JTextField();
        btnRegistrarPrd = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        lblPuntos = new javax.swing.JLabel();
        txtPuntos = new javax.swing.JTextField();
        panelFarmacias = new javax.swing.JPanel();
        lblCod = new javax.swing.JLabel();
        txtCodigoFarmacia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbldescripcion = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        txtDescripcionFarmacia = new javax.swing.JTextField();
        txtTelefonoFarmacia = new javax.swing.JTextField();
        btnRegistrarFarmacia = new javax.swing.JButton();
        btnConsultarFarmacia = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaFarmacias = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        lblTelCliente = new javax.swing.JLabel();
        lblCorreoCliente = new javax.swing.JLabel();
        txtCedulaCliente = new javax.swing.JTextField();
        txtNombreCliente = new javax.swing.JTextField();
        txtTelCliente = new javax.swing.JTextField();
        txtCorreoCliente = new javax.swing.JTextField();
        txtApelllCliente = new javax.swing.JTextField();
        btnAgregarCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Descripción", "Unidades Req.", "Puntos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        lblCodigo.setText("Codigo");

        lblDescripcion.setText("Descripcion");

        lblUnidades.setText("Unidades requeridas");

        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });

        btnRegistrarPrd.setText("Registrar");
        btnRegistrarPrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPrdActionPerformed(evt);
            }
        });

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        lblPuntos.setText("Puntos ");

        javax.swing.GroupLayout panelProductosLayout = new javax.swing.GroupLayout(panelProductos);
        panelProductos.setLayout(panelProductosLayout);
        panelProductosLayout.setHorizontalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelProductosLayout.createSequentialGroup()
                        .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelProductosLayout.createSequentialGroup()
                                .addComponent(lblUnidades)
                                .addGap(28, 28, 28)
                                .addComponent(spUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPuntos))
                            .addGroup(panelProductosLayout.createSequentialGroup()
                                .addComponent(lblCodigo)
                                .addGap(75, 75, 75)
                                .addComponent(txtCodigoPrd, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDescripcion)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelProductosLayout.createSequentialGroup()
                        .addComponent(btnRegistrarPrd)
                        .addGap(37, 37, 37)
                        .addComponent(btnConsultar))
                    .addComponent(jScrollPane2))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panelProductosLayout.setVerticalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductosLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescripcion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCodigo)
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCodigoPrd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUnidades)
                    .addComponent(spUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPuntos)
                    .addComponent(txtPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarPrd)
                    .addComponent(btnConsultar))
                .addGap(51, 51, 51)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Productos", panelProductos);

        lblCod.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblCod.setText("Código:");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("FARMACIAS");

        lbldescripcion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbldescripcion.setText("Descripción:");

        lblTelefono.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTelefono.setText("Teléfono:");

        btnRegistrarFarmacia.setText("REGISTRAR FARMACIA");
        btnRegistrarFarmacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarFarmaciaActionPerformed(evt);
            }
        });

        btnConsultarFarmacia.setText("CONSULTAR FARMACIA");
        btnConsultarFarmacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarFarmaciaActionPerformed(evt);
            }
        });

        tablaFarmacias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Descripción", "Teléfono"
            }
        ));
        jScrollPane3.setViewportView(tablaFarmacias);

        javax.swing.GroupLayout panelFarmaciasLayout = new javax.swing.GroupLayout(panelFarmacias);
        panelFarmacias.setLayout(panelFarmaciasLayout);
        panelFarmaciasLayout.setHorizontalGroup(
            panelFarmaciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFarmaciasLayout.createSequentialGroup()
                .addGroup(panelFarmaciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFarmaciasLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(panelFarmaciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFarmaciasLayout.createSequentialGroup()
                                .addComponent(lblCod)
                                .addGap(18, 18, 18)
                                .addComponent(txtCodigoFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelFarmaciasLayout.createSequentialGroup()
                                .addComponent(lblTelefono)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTelefonoFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(58, 58, 58)
                        .addGroup(panelFarmaciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFarmaciasLayout.createSequentialGroup()
                                .addComponent(lbldescripcion)
                                .addGap(18, 18, 18)
                                .addComponent(txtDescripcionFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)))
                    .addGroup(panelFarmaciasLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btnRegistrarFarmacia)
                        .addGap(18, 18, 18)
                        .addComponent(btnConsultarFarmacia))
                    .addGroup(panelFarmaciasLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        panelFarmaciasLayout.setVerticalGroup(
            panelFarmaciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFarmaciasLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(panelFarmaciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCod)
                    .addComponent(txtCodigoFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldescripcion)
                    .addComponent(txtDescripcionFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(panelFarmaciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono)
                    .addComponent(txtTelefonoFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(panelFarmaciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarFarmacia)
                    .addComponent(btnConsultarFarmacia))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Farmacias", panelFarmacias);

        lblNombre.setText("Nombre: ");

        lblApellido.setText("Apellidos:");

        lblCedula.setText("Cedula:");

        lblTelCliente.setText("Teléfono:");

        lblCorreoCliente.setText("Correo:");

        btnAgregarCliente.setText("Agregar");

        tableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cédula", "Nombre", "Teléfono", "Correo"
            }
        ));
        jScrollPane1.setViewportView(tableClientes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTelCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCorreoCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCorreoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblCedula)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblNombre)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(27, 27, 27)
                                .addComponent(lblApellido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtApelllCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedula)
                    .addComponent(txtCedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApellido)
                    .addComponent(txtApelllCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelCliente)
                    .addComponent(txtTelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreoCliente)
                    .addComponent(txtCorreoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btnAgregarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jTabbedPane1.addTab("Clientes", jPanel1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void btnRegistrarPrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPrdActionPerformed
        
        // revisa las condiciones de ingreso de los datos y hace verificaciones
        
        
        int codigo = Integer.parseInt(txtCodigoPrd.getText());
        String descripcion = txtDescripcion.getText();
        int unidades = (int) spUnidades.getValue();
        int puntos = Integer.parseInt(txtPuntos.getText());
        
        
        // se carga el DTO que está en el controlador... 
        elCtrl.getdTOProductos().getUnProducto().setCodigo(codigo);
        elCtrl.getdTOProductos().getUnProducto().setDescripcion(descripcion);
        elCtrl.getdTOProductos().getUnProducto().setUnidadesReq(unidades);
        elCtrl.getdTOProductos().getUnProducto().setPuntos(puntos);
        
        boolean resultado = elCtrl.registrarProducto();
       
        System.out.println(resultado? "ingreso producto" : "problemas para ingresar producto");
        
        cargaTablaProductos();
    }//GEN-LAST:event_btnRegistrarPrdActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        int codigo = Integer.parseInt(txtCodigoPrd.getText());
        elCtrl.getdTOProductos().getUnProducto().setCodigo(codigo);
        boolean respuesta = elCtrl.recuperarProducto();
        if (respuesta){
            txtDescripcion.setText(""+ elCtrl.getdTOProductos().getUnProducto().getDescripcion());
            txtPuntos.setText(""+ elCtrl.getdTOProductos().getUnProducto().getPuntos());
            spUnidades.setValue(elCtrl.getdTOProductos().getUnProducto().getUnidadesReq());
            System.out.println("mostrar el contenido del producto");
        }
        else{
            System.out.println("reportar que el producto no existe.");
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnRegistrarFarmaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarFarmaciaActionPerformed
        // TODO add your handling code here:
        int codigoFarmacia = Integer.parseInt(txtCodigoFarmacia.getText());
        String descripcionFarmacia = txtDescripcionFarmacia.getText();
        String telefonoFarmacia = txtTelefonoFarmacia.getText();

        dtoFarmacia.getUnaFarmacia().setCodigo(codigoFarmacia);
        dtoFarmacia.getUnaFarmacia().setDescripcion(descripcionFarmacia);
        dtoFarmacia.getUnaFarmacia().setTelefono(telefonoFarmacia);

        boolean resultado = elCtrl.registrarFarmacia(dtoFarmacia);

        System.out.println(resultado? "ingreso farmacia" : "problemas para ingresar farmacia");
        
        cargaTablaFarmacias();

    }//GEN-LAST:event_btnRegistrarFarmaciaActionPerformed

    private void btnConsultarFarmaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarFarmaciaActionPerformed
        // TODO add your handling code here:
        int codigoFarmacia = Integer.parseInt(txtCodigoFarmacia.getText());
        dtoFarmacia.getUnaFarmacia().setCodigo(codigoFarmacia);
        dtoFarmacia = elCtrl.recuperarFarmacia(dtoFarmacia);
        Farmacia laFarm = dtoFarmacia.getUnaFarmacia();
        if (laFarm != null){
            dtoFarmacia.setUnaFarmacia(laFarm);
            txtDescripcionFarmacia.setText(dtoFarmacia.getUnaFarmacia().getDescripcion());
            txtTelefonoFarmacia.setText(dtoFarmacia.getUnaFarmacia().getTelefono());
        }
        else{
            System.out.println("reportar que la farmacia no existe.");
        }

    }//GEN-LAST:event_btnConsultarFarmaciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCatalogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCatalogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCatalogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCatalogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCatalogos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnConsultarFarmacia;
    private javax.swing.JButton btnRegistrarFarmacia;
    private javax.swing.JButton btnRegistrarPrd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCod;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCorreoCliente;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPuntos;
    private javax.swing.JLabel lblTelCliente;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblUnidades;
    private javax.swing.JLabel lbldescripcion;
    private javax.swing.JPanel panelFarmacias;
    private javax.swing.JPanel panelProductos;
    private javax.swing.JSpinner spUnidades;
    private javax.swing.JTable tablaFarmacias;
    private javax.swing.JTable tableClientes;
    private javax.swing.JTextField txtApelllCliente;
    private javax.swing.JTextField txtCedulaCliente;
    private javax.swing.JTextField txtCodigoFarmacia;
    private javax.swing.JTextField txtCodigoPrd;
    private javax.swing.JTextField txtCorreoCliente;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtDescripcionFarmacia;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtPuntos;
    private javax.swing.JTextField txtTelCliente;
    private javax.swing.JTextField txtTelefonoFarmacia;
    // End of variables declaration//GEN-END:variables
}
